let backend = [
  {
    id: 339,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/posters/2022/10/20/d7d327f0-1ae2-4f53-8313-5741e46e86bd.jpg",
    title: "Типа крутые легавые",
    title_en: "Hot Fuzz",
    year: 2007,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 6,
        title: "Детектив",
        order_position: 6,
      },
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
    ],
  },
  {
    id: 458,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/posters/2022/06/20/c2acc31e-0b51-4ed2-b6be-684a9cd9f330.jpg",
    title: "Формула любви для узников брака",
    title_en: "Couples Retreat",
    year: 2009,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
    ],
  },
  {
    id: 274,
    moduleId: 31,
    cardType: "moretv",
    poster: "https://files.cinerama.uz/images/2011/06/25/4f049c0840189.jpg",
    title: "Астробой",
    title_en: "Astro Boy",
    year: 2009,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 23,
        title: "Мультфильм",
        order_position: 23,
      },
      {
        id: 37,
        title: "Семейный",
        order_position: 37,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 376,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/posters/2022/04/02/6437b299-cbbc-4c1e-afe3-8a50123ea8a3.jpg",
    title: "Шрек 2",
    title_en: "Shrek 2",
    year: 2004,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
      {
        id: 23,
        title: "Мультфильм",
        order_position: 23,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 37,
        title: "Семейный",
        order_position: 37,
      },
      {
        id: 47,
        title: "Фэнтези",
        order_position: 46,
      },
    ],
  },
  {
    id: 404,
    moduleId: 17,
    cardType: "amediateka",
    poster:
      "https://files.cinerama.uz/images/posters/2022/02/16/ed812a0e-9382-42a4-9d7a-e458a2911c4c.jpg",
    title: "Звездный путь",
    title_en: "Star Trek",
    year: 2009,
    quality: "full_hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 211,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/04/30/4f049bd0b9985.jpg",
    title: "Всё путём",
    title_en: "Everybody's Fine",
    year: 2009,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
    ],
  },
  {
    id: 511,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/25/4f04aef450177.jpg",
    title: "Мегамозг",
    title_en: "Megamind",
    year: 2010,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
      {
        id: 23,
        title: "Мультфильм",
        order_position: 23,
      },
      {
        id: 37,
        title: "Семейный",
        order_position: 37,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 572,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/2011/08/10/4f04b0b806c313.21034962.jpg",
    title: "Двойной форсаж",
    title_en: "2 Fast 2 Furious",
    year: 2003,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 553,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/2011/07/25/4f04b09d50b477.39848290.jpg",
    title: "Радиоволна",
    title_en: "Frequency",
    year: 2000,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 463,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/21/4f04adf23b94f.jpg",
    title: "Город Эмбер: Побег",
    title_en: "City of Ember",
    year: 2008,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 37,
        title: "Семейный",
        order_position: 37,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
      {
        id: 47,
        title: "Фэнтези",
        order_position: 46,
      },
    ],
  },
  {
    id: 528,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/25/4f04af5361b94.jpg",
    title: "В джазе только девушки",
    title_en: "Some Like It Hot",
    year: 1959,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 20,
        title: "Мелодрама",
        order_position: 20,
      },
      {
        id: 22,
        title: "Музыка",
        order_position: 22,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
    ],
  },
  {
    id: 539,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/2011/07/25/4f04b078e43990.22025664.jpg",
    title: "Джонни Д",
    title_en: "Public Enemies",
    year: 2009,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 2,
        title: "Биография",
        order_position: 2,
      },
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 13,
        title: "История",
        order_position: 13,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 480,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/22/4f04ae693bb7b.jpg",
    title: "Большая игра",
    title_en: "State of Play",
    year: 2009,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 6,
        title: "Детектив",
        order_position: 6,
      },
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 419,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ac6ebdc45.jpg",
    title: "Адреналин: Высокое напряжение",
    title_en: "Crank: High Voltage",
    year: 2009,
    quality: "full_hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 47,
        title: "Фэнтези",
        order_position: 46,
      },
    ],
  },
  {
    id: 295,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/06/25/4f049c26a3c66.jpg",
    title: "Мгла",
    title_en: "The Mist",
    year: 2007,
    quality: "full_hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
      {
        id: 44,
        title: "Ужасы",
        order_position: 43,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 398,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/2016/01/23/56a309df1b53e0.32117853.jpg",
    title: "Шрек мороз, зеленый нос",
    title_en: "Shrek the Halls",
    year: 2007,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
      {
        id: 17,
        title: "Короткометражка",
        order_position: 17,
      },
      {
        id: 23,
        title: "Мультфильм",
        order_position: 23,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 47,
        title: "Фэнтези",
        order_position: 46,
      },
    ],
  },
  {
    id: 395,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ac1806f92.jpg",
    title: "Особо опасен",
    title_en: "Wanted",
    year: 2008,
    quality: "full_hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 388,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ab4376835.jpg",
    title: "Вертикальный предел",
    title_en: "Vertical Limit",
    year: 2000,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 387,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ab3da3fff.jpg",
    title: "Водный мир",
    title_en: "Waterworld",
    year: 1995,
    quality: "full_hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 391,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ab4606b2a.jpg",
    title: "Машина времени",
    title_en: "The Time Machine",
    year: 2002,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 351,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/01/4f04aadcba23d.jpg",
    title: "Рэмбо IV",
    title_en: "Rambo",
    year: 2008,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 5,
        title: "Военный",
        order_position: 5,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 493,
    moduleId: 31,
    cardType: "moretv",
    poster: "https://files.cinerama.uz/images/2011/07/22/4f04ae9e087f3.jpg",
    title: "Посылка",
    title_en: "The Box",
    year: 2009,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 6,
        title: "Детектив",
        order_position: 6,
      },
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 380,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ab2f68ff4.jpg",
    title: "Халк",
    title_en: "Hulk",
    year: 2003,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 383,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ab3863b14.jpg",
    title: "Пророк",
    title_en: "Next",
    year: 2007,
    quality: "full_hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 20,
        title: "Мелодрама",
        order_position: 20,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
      {
        id: 47,
        title: "Фэнтези",
        order_position: 46,
      },
    ],
  },
  {
    id: 379,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/07/4f04ab24a2647.jpg",
    title: "Завтра не умрет никогда",
    title_en: "Tomorrow Never Dies",
    year: 1997,
    quality: "hd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 31,
        title: "Приключения",
        order_position: 31,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 250,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/04/30/4f049bed9e780.jpg",
    title: "Забирая жизни",
    title_en: "Taking Lives",
    year: 2004,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 6,
        title: "Детектив",
        order_position: 6,
      },
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 18,
        title: "Криминал",
        order_position: 18,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
      {
        id: 44,
        title: "Ужасы",
        order_position: 43,
      },
    ],
  },
  {
    id: 327,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/06/29/4f049c54ee843.jpg",
    title: "Олдбой",
    title_en: "Oldeuboi",
    year: 2003,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 6,
        title: "Детектив",
        order_position: 6,
      },
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
    ],
  },
  {
    id: 459,
    moduleId: 3,
    cardType: "cinerama",
    poster: "https://files.cinerama.uz/images/2011/07/21/4f04ade83be62.jpg",
    title: "Безумцы",
    title_en: "The Crazies",
    year: 2010,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
      {
        id: 44,
        title: "Ужасы",
        order_position: 43,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 540,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/2011/07/25/4f04b08b1d44e1.78380397.jpg",
    title: "Пятое измерение",
    title_en: "Push",
    year: 2009,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 3,
        title: "Боевик",
        order_position: 3,
      },
      {
        id: 43,
        title: "Триллер",
        order_position: 42,
      },
      {
        id: 45,
        title: "Фантастика",
        order_position: 44,
      },
    ],
  },
  {
    id: 594,
    moduleId: 3,
    cardType: "cinerama",
    poster:
      "https://files.cinerama.uz/images/2011/08/17/4f04b11c9c0581.70529781.jpg",
    title: "Больше, чем друг",
    title_en: "The Switch",
    year: 2010,
    quality: "sd",
    age_limit: 0,
    is_serial: false,
    is_new: false,
    is_favourite: false,
    genres: [
      {
        id: 9,
        title: "Драма",
        order_position: 9,
      },
      {
        id: 15,
        title: "Комедия",
        order_position: 15,
      },
      {
        id: 20,
        title: "Мелодрама",
        order_position: 20,
      },
    ],
  },
];

export default backend;
